#!/bin/bash

# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
echo "Seleccione el modo de ejecución:"
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
echo "1) Local"
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
echo "2) Remoto"
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
read -p "Opción (1/2): " mode
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
if [ "$mode" == "1" ]; then
    FLAG="--local"
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
elif [ "$mode" == "2" ]; then
    echo "Que estas intentando hacer? No borres la base de datos de produccion, por favor."
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
    echo "Si necesitas hacer cambios, habla con rocka."
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
    exit 1
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
else
    echo "Opción inválida. Saliendo."
    exit 1
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
fi
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# npx wrangler r2 object put v2-ramos/2025-1.json -f ./json/2025-1.json $FLAG
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
npx wrangler d1 execute v2-ramos $FLAG --file=./sql/main.sql -y
echo "main ready"
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
echo "Insertando cursos"
for file in ./sql/courses/*.sql; do
    echo "Ejecutando $file..."
    npx wrangler d1 execute v2-ramos $FLAG --file="$file" -y
done
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO, SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS
# NO COPIAR ESTE ARCHIVO PARA CREAR OTRO SI SE TE PASAN COSAS SIN REVISAR PUEDES MATAR LA BASE DE DATOS