name: Dev Cloudflare Worker

on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    if: github.ref == 'refs/heads/deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run build and deploy
        env:
          API_SECRET: ${{ secrets.API_SECRET }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npm run deploy
