name: PR Preview Check

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]

jobs:
  preview-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup environment variables
        run: |
          echo "MODE_ENV=development" > .env.local
          echo "API_SECRET=${{ secrets.API_SECRET || 'test_secret_for_ci' }}" >> .env.local
          echo "USER_TOKEN=${{ secrets.USER_TOKEN || 'test_token_for_ci' }}" >> .env.local

      - name: Setup local database
        run: |
          cd migration
          # Automatically select local mode (option 1) for CI
          echo "1" | bash setup.sh
          cd ..

      - name: Check preview build
        run: |
          # Run the preview command with a timeout to prevent hanging
          timeout 300s npm run preview &
          PREVIEW_PID=$!
          
          # Wait a bit for the server to start
          sleep 30
          
          # Check if the process is still running (means it started successfully)
          if kill -0 $PREVIEW_PID 2>/dev/null; then
            echo "✅ Preview server started successfully"
            kill $PREVIEW_PID
            exit 0
          else
            echo "❌ Preview server failed to start"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: |
          # Kill any remaining processes
          pkill -f "wrangler pages dev" || true
          pkill -f "astro build" || true
